import { DurableMutationError, SerializedMutationQueue } from "@/services/storage/durableMutation";
import { mealPlanStorageDefinition } from "@/services/storage/domainSchemas";
import { loadVersionedData, saveVersionedData } from "@/services/storage/versionedStorage";
import { isLocalDateKey } from "@/utils/dateTime";
import * as recipes from "@/features/recipes/services/recipeLocalRepository";
import * as groceries from "@/features/groceries/services/groceryLocalRepository";
import { mealSlots, type PlannedMealAssignment, type PlannedMealInput, type WeeklyMealPlan } from "../types/mealPlan";
const queue = new SerializedMutationQueue(); const all = () => loadVersionedData(mealPlanStorageDefinition).data; const save = (v: WeeklyMealPlan[]) => saveVersionedData(mealPlanStorageDefinition, v); const id = (p: string) => `${p}_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`;
export function weekStartFor(date: string): string { const [year, month, day] = date.split("-").map(Number); const d = new Date(Date.UTC(year, month - 1, day)); d.setUTCDate(d.getUTCDate() - ((d.getUTCDay() + 6) % 7)); return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, "0")}-${String(d.getUTCDate()).padStart(2, "0")}`; }
export async function getPlan(weekStart: string): Promise<WeeklyMealPlan> { await queue.waitForIdle(); const found = all().find((p) => p.weekStart === weekStart); if (found) return found; const now = new Date().toISOString(); return { id: id("plan"), weekStart, assignments: [], createdAt: now, updatedAt: now, version: 1 }; }
export function saveAssignment(weekStart: string, input: PlannedMealInput, assignmentId?: string): Promise<WeeklyMealPlan> { return queue.run(async () => { if (!isLocalDateKey(weekStart) || weekStartFor(input.date) !== weekStart || !mealSlots.includes(input.slot)) throw new DurableMutationError("meal-plans", "update", "invalid-input", "Choose a valid day and meal slot."); let snapshot: PlannedMealAssignment["recipeSnapshot"]; if (input.recipeId) { const recipe = await recipes.getRecipe(input.recipeId); if (!recipe) throw new DurableMutationError("meal-plans", "update", "not-found", "That recipe is no longer available."); snapshot = { name: recipe.name, ingredients: recipe.ingredients.map(({ name, quantity, unit }) => ({ name, quantity, unit })) }; } else if (!input.manualDescription?.trim()) throw new DurableMutationError("meal-plans", "update", "invalid-input", "Choose a recipe or write a meal description."); const records = all(); const pos = records.findIndex((p) => p.weekStart === weekStart); const now = new Date().toISOString(); const plan = pos >= 0 ? records[pos] : { id: id("plan"), weekStart, assignments: [], createdAt: now, updatedAt: now, version: 1 }; if (plan.assignments.some((a) => a.date === input.date && a.slot === input.slot && a.id !== assignmentId)) throw new DurableMutationError("meal-plans", "update", "invalid-input", "That meal slot already has an assignment."); const prior = plan.assignments.find((a) => a.id === assignmentId); const assignment: PlannedMealAssignment = { id: assignmentId ?? id("assignment"), date: input.date, slot: input.slot, recipeId: input.recipeId, recipeSnapshot: snapshot, manualDescription: input.recipeId ? undefined : input.manualDescription?.trim(), createdAt: prior?.createdAt ?? now, updatedAt: now }; const updated = { ...plan, assignments: prior ? plan.assignments.map((a) => a.id === assignmentId ? assignment : a) : [...plan.assignments, assignment], updatedAt: now, version: plan.version + (pos >= 0 ? 1 : 0) }; if (pos >= 0) records[pos] = updated; else records.push(updated); save(records); return updated; }); }
export function removeAssignment(weekStart: string, assignmentId: string): Promise<WeeklyMealPlan> { return queue.run(async () => { const records = all(); const i = records.findIndex((p) => p.weekStart === weekStart); if (i < 0) throw new DurableMutationError("meal-plans", "delete", "not-found", "That meal plan no longer exists."); const updated = { ...records[i], assignments: records[i].assignments.filter((a) => a.id !== assignmentId), updatedAt: new Date().toISOString(), version: records[i].version + 1 }; records[i] = updated; save(records); return updated; }); }
export async function generateGroceries(weekStart: string): Promise<void> { const plan = await getPlan(weekStart); await groceries.upsertGeneratedGroceries(plan.assignments.flatMap((a) => (a.recipeSnapshot?.ingredients ?? []).map((i) => ({ ...i, sourceId: a.id })))); }
