import * as repository from "@/features/measurements/services/measurementRepository";
import { measurementHistoryForType } from "@/features/measurements/services/measurementSelectors";
import { formatMeasurementValue, parseMeasurementValue } from "@/features/measurements/services/measurementValue";
import { useMeasurementStore } from "@/features/measurements/store/useMeasurementStore";
import { DurableMutationError } from "@/services/storage/durableMutation";
import { deleteKey } from "@/services/storage/mmkv";
import { StorageKeys } from "@/services/storage/storageKeys";
import { assert, assertEqual } from "../testUtils";

function reset(): void { deleteKey(StorageKeys.BODY_MEASUREMENTS); useMeasurementStore.setState({ measurements: [], isHydrated: false, isLoading: false, isSaving: false, error: null }); }
export function testMeasurementUnitsAndPrecision(): void { assertEqual(parseMeasurementValue("82.125"), 82125, "three decimal places use exact integer storage"); assertEqual(formatMeasurementValue(82125), "82.125", "stored values format without precision loss"); assertEqual(parseMeasurementValue("82.1234"), null, "excess precision is rejected"); assertEqual(parseMeasurementValue("0"), null, "zero is rejected"); }
export async function testMeasurementPerTypeHistoryEditDeleteAndRestart(): Promise<void> { reset(); const waist = await repository.createMeasurement({ type: "waist", valueMilli: 82000, unit: "cm", date: "2026-09-01" }); await repository.createMeasurement({ type: "chest", valueMilli: 36000, unit: "in", date: "2026-09-03" }); await repository.updateMeasurement(waist.id, { type: "waist", valueMilli: 81500, unit: "cm", date: "2026-09-04" }); const values = await repository.getMeasurements(); assertEqual(measurementHistoryForType(values, "waist")[0].valueMilli, 81500, "per-type history reflects edits"); assertEqual(measurementHistoryForType(values, "chest").length, 1, "per-type history excludes other types"); await useMeasurementStore.getState().hydrate(); assertEqual(useMeasurementStore.getState().measurements.length, 2, "measurement records survive restart hydration"); await repository.deleteMeasurement(waist.id); assertEqual(measurementHistoryForType(await repository.getMeasurements(), "waist").length, 0, "deletion removes the record from its history"); }
export async function testMeasurementValidation(): Promise<void> { reset(); for (const input of [{ type: "waist" as const, valueMilli: -1, unit: "cm" as const, date: "2026-09-01" }, { type: "waist" as const, valueMilli: 1000, unit: "cm" as const, date: "invalid" }]) { let failure: unknown; try { await repository.createMeasurement(input); } catch (error) { failure = error; } assert(failure instanceof DurableMutationError, "invalid measurement input is rejected"); } }
