import { DurableMutationError, SerializedMutationQueue, type DurableMutationOperation } from "@/services/storage/durableMutation";
import { recipeStorageDefinition } from "@/services/storage/domainSchemas";
import { loadVersionedData, saveVersionedData } from "@/services/storage/versionedStorage";
import type { Recipe, RecipeInput } from "../types/recipe";
const queue = new SerializedMutationQueue(); const id = (prefix: string) => `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`;
const all = () => loadVersionedData(recipeStorageDefinition).data; const save = (data: Recipe[]) => saveVersionedData(recipeStorageDefinition, data);
function validate(input: RecipeInput, operation: DurableMutationOperation): RecipeInput { const name = input.name.trim(); const instructions = input.instructions.trim(); if (!name) throw new DurableMutationError("recipes", operation, "invalid-input", "A recipe needs a name."); if (!Number.isFinite(input.servings) || input.servings <= 0) throw new DurableMutationError("recipes", operation, "invalid-input", "Servings must be greater than zero."); if (!instructions) throw new DurableMutationError("recipes", operation, "invalid-input", "Add recipe instructions."); if (!input.ingredients.length) throw new DurableMutationError("recipes", operation, "invalid-input", "Add at least one ingredient."); const ingredients = input.ingredients.map((ingredient) => ({ ...ingredient, name: ingredient.name.trim(), unit: ingredient.unit.trim() })); if (ingredients.some((i) => !i.name || !i.unit || !Number.isFinite(i.quantity) || i.quantity <= 0)) throw new DurableMutationError("recipes", operation, "invalid-input", "Each ingredient needs a name, positive quantity and unit."); return { name, servings: input.servings, instructions, ingredients }; }
function mutate<T>(operation: DurableMutationOperation, work: () => T): Promise<T> { return queue.run(() => { try { return work(); } catch (cause) { if (cause instanceof DurableMutationError) throw cause; throw new DurableMutationError("recipes", operation, "write-failed", "Recipe changes could not be saved.", cause); } }); }
export async function getRecipes(): Promise<Recipe[]> { await queue.waitForIdle(); return all().filter((r) => !r.deletedAt); }
export async function getRecipe(idValue: string): Promise<Recipe | null> { return (await getRecipes()).find((r) => r.id === idValue) ?? null; }
export function createRecipe(input: RecipeInput): Promise<Recipe> { return mutate("create", () => { const valid = validate(input, "create"); const now = new Date().toISOString(); const recipe: Recipe = { ...valid, ingredients: valid.ingredients.map((ingredient) => ({ ...ingredient, id: id("ingredient") })), id: id("recipe"), createdAt: now, updatedAt: now, deletedAt: null, version: 1 }; save([...all(), recipe]); return recipe; }); }
export function updateRecipe(idValue: string, input: RecipeInput): Promise<Recipe> { return mutate("update", () => { const valid = validate(input, "update"); const records = all(); const index = records.findIndex((r) => r.id === idValue && !r.deletedAt); if (index < 0) throw new DurableMutationError("recipes", "update", "not-found", "That recipe no longer exists."); const old = records[index]; const updated: Recipe = { ...old, ...valid, ingredients: valid.ingredients.map((ingredient, i) => ({ ...ingredient, id: old.ingredients[i]?.id ?? id("ingredient") })), updatedAt: new Date().toISOString(), version: old.version + 1 }; records[index] = updated; save(records); return updated; }); }
export function deleteRecipe(idValue: string): Promise<void> { return mutate("delete", () => { const records = all(); const index = records.findIndex((r) => r.id === idValue && !r.deletedAt); if (index < 0) return; const old = records[index]; records[index] = { ...old, deletedAt: new Date().toISOString(), updatedAt: new Date().toISOString(), version: old.version + 1 }; save(records); }); }
