import { DurableMutationError, SerializedMutationQueue, type DurableMutationOperation } from "@/services/storage/durableMutation";
import { workoutStorageDefinition } from "@/services/storage/domainSchemas";
import { loadVersionedData, saveVersionedData } from "@/services/storage/versionedStorage";
import { isLocalDateKey } from "@/utils/dateTime";
import type { Workout, WorkoutInput } from "../types/workout";
const queue = new SerializedMutationQueue(); const load = () => loadVersionedData(workoutStorageDefinition).data; const save = (values: Workout[]) => saveVersionedData(workoutStorageDefinition, values);
function validate(input: WorkoutInput, operation: DurableMutationOperation): Required<WorkoutInput> { const activity = input.activity.trim(); if (!activity) throw new DurableMutationError("workouts", operation, "invalid-input", "Enter an activity."); if (!isLocalDateKey(input.date)) throw new DurableMutationError("workouts", operation, "invalid-input", "Choose a valid local date."); if (!Number.isSafeInteger(input.durationMinutes) || input.durationMinutes <= 0) throw new DurableMutationError("workouts", operation, "invalid-input", "Duration must be a positive whole number of minutes."); const calorieEstimate = input.calorieEstimate ?? null; if (calorieEstimate !== null && (!Number.isSafeInteger(calorieEstimate) || calorieEstimate < 0)) throw new DurableMutationError("workouts", operation, "invalid-input", "Optional calories must be a whole number zero or greater."); return { activity, date: input.date, durationMinutes: input.durationMinutes, calorieEstimate }; }
function mutate<T>(operation: DurableMutationOperation, work: () => T): Promise<T> { return queue.run(() => { try { return work(); } catch (cause) { if (cause instanceof DurableMutationError) throw cause; throw new DurableMutationError("workouts", operation, "write-failed", "Workout changes could not be saved.", cause); } }); }
export async function getWorkouts(): Promise<Workout[]> { await queue.waitForIdle(); return load().filter((value) => !value.deletedAt); }
export function createWorkout(input: WorkoutInput): Promise<Workout> { return mutate("create", () => { const valid = validate(input, "create"); const now = new Date().toISOString(); const value = { ...valid, id: `workout_${Date.now()}_${Math.random().toString(36).slice(2, 10)}`, createdAt: now, updatedAt: now, deletedAt: null, version: 1 }; save([...load(), value]); return value; }); }
export function updateWorkout(id: string, input: WorkoutInput): Promise<Workout> { return mutate("update", () => { const valid = validate(input, "update"); const values = load(); const index = values.findIndex((value) => value.id === id && !value.deletedAt); if (index < 0) throw new DurableMutationError("workouts", "update", "not-found", "That workout no longer exists."); values[index] = { ...values[index], ...valid, updatedAt: new Date().toISOString(), version: values[index].version + 1 }; save(values); return values[index]; }); }
export function deleteWorkout(id: string): Promise<void> { return mutate("delete", () => { const values = load(); const index = values.findIndex((value) => value.id === id && !value.deletedAt); if (index < 0) return; const now = new Date().toISOString(); values[index] = { ...values[index], deletedAt: now, updatedAt: now, version: values[index].version + 1 }; save(values); }); }
