import { DurableMutationError, SerializedMutationQueue, type DurableMutationOperation } from "@/services/storage/durableMutation";
import { groceryStorageDefinition } from "@/services/storage/domainSchemas";
import { loadVersionedData, saveVersionedData } from "@/services/storage/versionedStorage";
import type { GeneratedGroceryIngredient, GroceryInput, GroceryItem } from "../types/grocery";
import type { Recipe } from "@/features/recipes/types/recipe";
const queue = new SerializedMutationQueue(); const id = () => `grocery_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`; const all = () => loadVersionedData(groceryStorageDefinition).data; const save = (v: GroceryItem[]) => saveVersionedData(groceryStorageDefinition, v);
function valid(input: GroceryInput, op: DurableMutationOperation): GroceryInput { const name = input.name.trim(); const unit = input.unit.trim(); if (!name || !unit || !Number.isFinite(input.quantity) || input.quantity <= 0) throw new DurableMutationError("groceries", op, "invalid-input", "An item needs a name, positive quantity and unit."); return { name, unit, quantity: input.quantity }; }
function mutate<T>(op: DurableMutationOperation, work: () => T): Promise<T> { return queue.run(() => { try { return work(); } catch (e) { if (e instanceof DurableMutationError) throw e; throw new DurableMutationError("groceries", op, "write-failed", "Grocery changes could not be saved.", e); } }); }
export async function getGroceries(): Promise<GroceryItem[]> { await queue.waitForIdle(); return all().filter((v) => !v.deletedAt); }
export function createGrocery(input: GroceryInput): Promise<GroceryItem> { return mutate("create", () => { const v = valid(input, "create"); const now = new Date().toISOString(); const item: GroceryItem = { ...v, id: id(), checked: false, sourceIds: [], generated: false, manuallyModified: false, createdAt: now, updatedAt: now, deletedAt: null, version: 1 }; save([...all(), item]); return item; }); }
export function updateGrocery(idValue: string, input: GroceryInput): Promise<GroceryItem> { return mutate("update", () => { const v = valid(input, "update"); const records = all(); const i = records.findIndex((x) => x.id === idValue && !x.deletedAt); if (i < 0) throw new DurableMutationError("groceries", "update", "not-found", "That grocery item no longer exists."); records[i] = { ...records[i], ...v, manuallyModified: true, updatedAt: new Date().toISOString(), version: records[i].version + 1 }; save(records); return records[i]; }); }
export function toggleGrocery(idValue: string): Promise<GroceryItem> { return mutate("update", () => { const records = all(); const i = records.findIndex((x) => x.id === idValue && !x.deletedAt); if (i < 0) throw new DurableMutationError("groceries", "update", "not-found", "That grocery item no longer exists."); records[i] = { ...records[i], checked: !records[i].checked, updatedAt: new Date().toISOString(), version: records[i].version + 1 }; save(records); return records[i]; }); }
export function deleteGrocery(idValue: string): Promise<void> { return mutate("delete", () => { const records = all(); const i = records.findIndex((x) => x.id === idValue && !x.deletedAt); if (i < 0) return; records[i] = { ...records[i], deletedAt: new Date().toISOString(), updatedAt: new Date().toISOString(), version: records[i].version + 1 }; save(records); }); }
function normalized(value: string): string { return value.trim().toLowerCase(); }
function upsertGenerated(records: GroceryItem[], ingredients: GeneratedGroceryIngredient[]): void { const desired = new Map<string, GeneratedGroceryIngredient>(); for (const ingredient of ingredients) { const prior = desired.get(ingredient.sourceId); desired.set(ingredient.sourceId, { ...ingredient, quantity: (prior?.quantity ?? 0) + ingredient.quantity }); } for (const ingredient of desired.values()) { const legacy = ingredient.legacySourceId ? records.filter((x) => !x.deletedAt && x.sourceIds.includes(ingredient.legacySourceId!)) : []; const exact = records.find((x) => x.sourceIds.includes(ingredient.sourceId)); if (exact?.deletedAt) continue; const matchingLegacy = legacy.find((x) => normalized(x.name) === normalized(ingredient.name) && normalized(x.unit) === normalized(ingredient.unit)); const found = exact ?? matchingLegacy ?? (legacy.length === 1 ? legacy[0] : undefined) ?? records.find((x) => !x.deletedAt && normalized(x.name) === normalized(ingredient.name) && normalized(x.unit) === normalized(ingredient.unit)); if (found) { const alreadyLinked = found.sourceIds.includes(ingredient.sourceId); if (ingredient.legacySourceId) found.sourceIds = found.sourceIds.filter((sourceId) => sourceId !== ingredient.legacySourceId); if (!alreadyLinked) found.sourceIds.push(ingredient.sourceId); if (exact && found.generated && !found.manuallyModified) { found.name = ingredient.name.trim(); found.quantity = ingredient.quantity; found.unit = ingredient.unit.trim(); found.updatedAt = new Date().toISOString(); found.version += 1; } else if (!alreadyLinked && found.generated && !found.manuallyModified) { found.quantity += ingredient.quantity; found.updatedAt = new Date().toISOString(); found.version += 1; } } else { const now = new Date().toISOString(); records.push({ id: id(), name: ingredient.name.trim(), quantity: ingredient.quantity, unit: ingredient.unit.trim(), checked: false, sourceIds: [ingredient.sourceId], generated: true, manuallyModified: false, createdAt: now, updatedAt: now, deletedAt: null, version: 1 }); } } }
/** Idempotent generation boundary: durable source IDs are matched before mutable display fields. */
export function upsertGeneratedGroceries(ingredients: GeneratedGroceryIngredient[]): Promise<void> { return mutate("update", () => { const records = all(); upsertGenerated(records, ingredients); save(records); }); }
/** Reconciles one planner's generated relationships without touching manual rows or manual edits. */
export function syncPlannerGroceries(sourcePrefix: string, ingredients: GeneratedGroceryIngredient[]): Promise<void> { return mutate("update", () => { const records = all(); const desired = new Set(ingredients.map((ingredient) => ingredient.sourceId)); const now = new Date().toISOString(); for (const record of records) { const retained = record.sourceIds.filter((sourceId) => !sourceId.startsWith(sourcePrefix) || desired.has(sourceId)); if (retained.length === record.sourceIds.length) continue; record.sourceIds = retained; record.updatedAt = now; record.version += 1; if (record.generated && !record.manuallyModified && retained.length === 0) record.deletedAt = now; } upsertGenerated(records, ingredients); save(records); }); }
export function addRecipeIngredients(recipe: Recipe): Promise<void> { return upsertGeneratedGroceries(recipe.ingredients.map(({ id: ingredientId, name, quantity, unit }) => ({ name, quantity, unit, sourceId: `recipe:${recipe.id}:ingredient:${ingredientId}`, legacySourceId: `recipe:${recipe.id}` }))); }
