import { DurableMutationError, SerializedMutationQueue, type DurableMutationOperation } from "@/services/storage/durableMutation";
import { groceryStorageDefinition } from "@/services/storage/domainSchemas";
import { loadVersionedData, saveVersionedData } from "@/services/storage/versionedStorage";
import type { GeneratedGroceryIngredient, GroceryInput, GroceryItem } from "../types/grocery";
import type { Recipe } from "@/features/recipes/types/recipe";
const queue = new SerializedMutationQueue(); const id = () => `grocery_${Date.now()}_${Math.random().toString(36).slice(2, 9)}`; const all = () => loadVersionedData(groceryStorageDefinition).data; const save = (v: GroceryItem[]) => saveVersionedData(groceryStorageDefinition, v);
function valid(input: GroceryInput, op: DurableMutationOperation): GroceryInput { const name = input.name.trim(); const unit = input.unit.trim(); if (!name || !unit || !Number.isFinite(input.quantity) || input.quantity <= 0) throw new DurableMutationError("groceries", op, "invalid-input", "An item needs a name, positive quantity and unit."); return { name, unit, quantity: input.quantity }; }
function mutate<T>(op: DurableMutationOperation, work: () => T): Promise<T> { return queue.run(() => { try { return work(); } catch (e) { if (e instanceof DurableMutationError) throw e; throw new DurableMutationError("groceries", op, "write-failed", "Grocery changes could not be saved.", e); } }); }
export async function getGroceries(): Promise<GroceryItem[]> { await queue.waitForIdle(); return all().filter((v) => !v.deletedAt); }
export function createGrocery(input: GroceryInput): Promise<GroceryItem> { return mutate("create", () => { const v = valid(input, "create"); const now = new Date().toISOString(); const item: GroceryItem = { ...v, id: id(), checked: false, sourceIds: [], generated: false, manuallyModified: false, createdAt: now, updatedAt: now, deletedAt: null, version: 1 }; save([...all(), item]); return item; }); }
export function updateGrocery(idValue: string, input: GroceryInput): Promise<GroceryItem> { return mutate("update", () => { const v = valid(input, "update"); const records = all(); const i = records.findIndex((x) => x.id === idValue && !x.deletedAt); if (i < 0) throw new DurableMutationError("groceries", "update", "not-found", "That grocery item no longer exists."); records[i] = { ...records[i], ...v, manuallyModified: true, updatedAt: new Date().toISOString(), version: records[i].version + 1 }; save(records); return records[i]; }); }
export function toggleGrocery(idValue: string): Promise<GroceryItem> { return mutate("update", () => { const records = all(); const i = records.findIndex((x) => x.id === idValue && !x.deletedAt); if (i < 0) throw new DurableMutationError("groceries", "update", "not-found", "That grocery item no longer exists."); records[i] = { ...records[i], checked: !records[i].checked, updatedAt: new Date().toISOString(), version: records[i].version + 1 }; save(records); return records[i]; }); }
export function deleteGrocery(idValue: string): Promise<void> { return mutate("delete", () => { const records = all(); const i = records.findIndex((x) => x.id === idValue && !x.deletedAt); if (i < 0) return; records[i] = { ...records[i], deletedAt: new Date().toISOString(), updatedAt: new Date().toISOString(), version: records[i].version + 1 }; save(records); }); }
/** Idempotent planner boundary: source IDs prevent repeated generation duplicates and manual edits win. */
export function upsertGeneratedGroceries(ingredients: GeneratedGroceryIngredient[]): Promise<void> { return mutate("update", () => { const records = all(); const desired = new Map<string, GeneratedGroceryIngredient>(); for (const ingredient of ingredients) { const key = `${ingredient.sourceId}|${ingredient.name.trim().toLowerCase()}|${ingredient.unit.trim().toLowerCase()}`; const prior = desired.get(key); desired.set(key, { ...ingredient, quantity: (prior?.quantity ?? 0) + ingredient.quantity }); } for (const ingredient of desired.values()) { const key = ingredient.name.trim().toLowerCase(); const found = records.find((x) => !x.deletedAt && x.name.trim().toLowerCase() === key && x.unit.trim().toLowerCase() === ingredient.unit.trim().toLowerCase()); if (found) { const alreadyLinked = found.sourceIds.includes(ingredient.sourceId); if (!alreadyLinked) found.sourceIds.push(ingredient.sourceId); if (!alreadyLinked && found.generated && !found.manuallyModified) { found.quantity += ingredient.quantity; found.updatedAt = new Date().toISOString(); found.version += 1; } } else { const now = new Date().toISOString(); records.push({ id: id(), name: ingredient.name.trim(), quantity: ingredient.quantity, unit: ingredient.unit.trim(), checked: false, sourceIds: [ingredient.sourceId], generated: true, manuallyModified: false, createdAt: now, updatedAt: now, deletedAt: null, version: 1 }); } } save(records); }); }
export function addRecipeIngredients(recipe: Recipe): Promise<void> { return upsertGeneratedGroceries(recipe.ingredients.map(({ name, quantity, unit }) => ({ name, quantity, unit, sourceId: `recipe:${recipe.id}` }))); }
