import * as repository from "@/features/meals/services/mealLocalRepository";
import { mealHistory, mealsForDate, nutritionTotals } from "@/features/meals/services/mealSelectors";
import { useMealStore } from "@/features/meals/store/useMealStore";
import { DurableMutationError } from "@/services/storage/durableMutation";
import { deleteKey } from "@/services/storage/mmkv";
import { StorageKeys } from "@/services/storage/storageKeys";
import { assert, assertEqual } from "../testUtils";

function reset(): void { deleteKey(StorageKeys.MEALS); useMealStore.setState({ meals: [], isHydrated: true, isLoading: false, error: null }); }
export async function testConsumedMealCrudHistoryAndRestart(): Promise<void> { reset(); const breakfast = await repository.createMeal({ name: "Oats", date: "2026-09-28", mealType: "breakfast", nutrition: { calories: 320 } }); const dinner = await repository.createMeal({ name: "Soup", date: "2026-09-27", mealType: "dinner" }); assertEqual(mealHistory(await repository.getMeals())[0].id, breakfast.id, "history should be newest date first"); const edited = await repository.updateMeal(breakfast.id, { name: "Oats and fruit", date: "2026-09-28", mealType: "breakfast", nutrition: { calories: 380, proteinGrams: 12 } }); assertEqual(edited.name, "Oats and fruit", "edits should persist"); useMealStore.setState({ meals: [], isHydrated: false }); await useMealStore.getState().hydrate(); assertEqual(useMealStore.getState().meals.length, 2, "restart hydration should restore entries"); await repository.deleteMeal(dinner.id); assertEqual((await repository.getMeals()).length, 1, "delete should remove the entry from active history"); }
export async function testDateBoundariesOptionalNutritionAndTotalsRecalculate(): Promise<void> { reset(); const noNutrition = await repository.createMeal({ name: "Tea", date: "2026-09-27", mealType: "snack" }); const today = await repository.createMeal({ name: "Lunch", date: "2026-09-28", mealType: "lunch", nutrition: { calories: 500, fatGrams: 10 } }); const meals = await repository.getMeals(); assertEqual(mealsForDate(meals, "2026-09-28").length, 1, "local date boundaries should not mix entries"); assertEqual(noNutrition.nutrition, undefined, "nutrition should remain genuinely optional"); assertEqual(nutritionTotals(mealsForDate(meals, "2026-09-28")).calories, 500, "totals should use persisted values only"); await repository.updateMeal(today.id, { name: "Lunch", date: "2026-09-28", mealType: "lunch", nutrition: { calories: 450 } }); assertEqual(nutritionTotals(await repository.getMeals()).calories, 450, "edits should recalculate totals"); await repository.deleteMeal(today.id); assertEqual(nutritionTotals(await repository.getMeals()).calories, 0, "deletes should recalculate totals"); }
export async function testMealValidationAndFailedSaveDoNotEnterMemory(): Promise<void> { reset(); let invalid: unknown; try { await repository.createMeal({ name: "", date: "bad", mealType: "snack", nutrition: { calories: -1 } }); } catch (error) { invalid = error; } assert(invalid instanceof DurableMutationError, "invalid meals should use durable validation"); const storage = globalThis.localStorage; const original = storage.setItem.bind(storage); storage.setItem = () => { throw new Error("disk full"); }; let failed: unknown; try { await useMealStore.getState().createMeal({ name: "Apple", date: "2026-09-28", mealType: "snack" }); } catch (error) { failed = error; } finally { storage.setItem = original; } assert(failed instanceof DurableMutationError, "failed writes should reject"); assertEqual(useMealStore.getState().meals.length, 0, "failed writes must not enter canonical memory"); }
