import { DurableMutationError, SerializedMutationQueue, type DurableMutationOperation } from "@/services/storage/durableMutation";
import { bodyMeasurementStorageDefinition } from "@/services/storage/domainSchemas";
import { loadVersionedData, saveVersionedData } from "@/services/storage/versionedStorage";
import { isLocalDateKey } from "@/utils/dateTime";
import { measurementTypes, type BodyMeasurement, type BodyMeasurementInput } from "../types/measurement";
const queue = new SerializedMutationQueue(); const load = () => loadVersionedData(bodyMeasurementStorageDefinition).data; const save = (values: BodyMeasurement[]) => saveVersionedData(bodyMeasurementStorageDefinition, values);
function validate(input: BodyMeasurementInput, operation: DurableMutationOperation): BodyMeasurementInput { if (!measurementTypes.includes(input.type)) throw new DurableMutationError("body-measurements", operation, "invalid-input", "Choose a supported measurement type."); if (input.unit !== "cm" && input.unit !== "in") throw new DurableMutationError("body-measurements", operation, "invalid-input", "Choose centimetres or inches."); if (!Number.isSafeInteger(input.valueMilli) || input.valueMilli <= 0) throw new DurableMutationError("body-measurements", operation, "invalid-input", "Measurement must be greater than zero."); if (!isLocalDateKey(input.date)) throw new DurableMutationError("body-measurements", operation, "invalid-input", "Choose a valid local date."); return input; }
function mutate<T>(operation: DurableMutationOperation, work: () => T): Promise<T> { return queue.run(() => { try { return work(); } catch (cause) { if (cause instanceof DurableMutationError) throw cause; throw new DurableMutationError("body-measurements", operation, "write-failed", "Measurement changes could not be saved.", cause); } }); }
export async function getMeasurements(): Promise<BodyMeasurement[]> { await queue.waitForIdle(); return load().filter((value) => !value.deletedAt); }
export function createMeasurement(input: BodyMeasurementInput): Promise<BodyMeasurement> { return mutate("create", () => { const valid = validate(input, "create"); const now = new Date().toISOString(); const value = { ...valid, id: `measurement_${Date.now()}_${Math.random().toString(36).slice(2, 10)}`, createdAt: now, updatedAt: now, deletedAt: null, version: 1 }; save([...load(), value]); return value; }); }
export function updateMeasurement(id: string, input: BodyMeasurementInput): Promise<BodyMeasurement> { return mutate("update", () => { const valid = validate(input, "update"); const values = load(); const index = values.findIndex((value) => value.id === id && !value.deletedAt); if (index < 0) throw new DurableMutationError("body-measurements", "update", "not-found", "That measurement no longer exists."); values[index] = { ...values[index], ...valid, updatedAt: new Date().toISOString(), version: values[index].version + 1 }; save(values); return values[index]; }); }
export function deleteMeasurement(id: string): Promise<void> { return mutate("delete", () => { const values = load(); const index = values.findIndex((value) => value.id === id && !value.deletedAt); if (index < 0) return; const now = new Date().toISOString(); values[index] = { ...values[index], deletedAt: now, updatedAt: now, version: values[index].version + 1 }; save(values); }); }
