import * as recipes from "@/features/recipes/services/recipeLocalRepository";
import * as groceries from "@/features/groceries/services/groceryLocalRepository";
import * as plans from "@/features/meal-plans/services/mealPlanLocalRepository";
import * as meals from "@/features/meals/services/mealLocalRepository";
import { deleteKey } from "@/services/storage/mmkv";
import { StorageKeys } from "@/services/storage/storageKeys";
import { assertEqual } from "../testUtils";
function reset() { [StorageKeys.RECIPES, StorageKeys.GROCERIES, StorageKeys.MEAL_PLANS, StorageKeys.MEALS].forEach(deleteKey); }
export async function testRecipeSnapshotSurvivesEditDeleteAndRestart(): Promise<void> { reset(); const recipe = await recipes.createRecipe({ name: "Pasta", servings: 2, ingredients: [{ name: "Tomato", quantity: 2, unit: "each" }], instructions: "Cook." }); const meal = await meals.createMealFromRecipe(recipe, { date: "2026-09-28", mealType: "dinner" }); await recipes.updateRecipe(recipe.id, { name: "Changed", servings: 4, ingredients: [{ name: "Salt", quantity: 1, unit: "tsp" }], instructions: "Changed." }); await recipes.deleteRecipe(recipe.id); assertEqual((await meals.getMealById(meal.id))?.recipeSnapshot?.name, "Pasta", "consumed meal retains a recipe snapshot"); }
export async function testGroceriesAreDurableCheckableAndGenerationIsIdempotent(): Promise<void> { reset(); const item = await groceries.createGrocery({ name: "Milk", quantity: 1, unit: "L" }); await groceries.toggleGrocery(item.id); assertEqual((await groceries.getGroceries())[0].checked, true, "checked state persists"); await groceries.upsertGeneratedGroceries([{ name: "Tomato", quantity: 2, unit: "each", sourceId: "assignment_1" }]); await groceries.upsertGeneratedGroceries([{ name: "Tomato", quantity: 2, unit: "each", sourceId: "assignment_1" }]); assertEqual((await groceries.getGroceries()).filter((x) => x.name === "Tomato").length, 1, "repeat generation does not duplicate ingredients"); }
export async function testRecipeIngredientImportPreservesManualItemsAndEdits(): Promise<void> { reset(); const manual = await groceries.createGrocery({ name: "Salt", quantity: 2, unit: "tsp" }); await groceries.updateGrocery(manual.id, { name: "Salt", quantity: 3, unit: "tsp" }); const recipe = await recipes.createRecipe({ name: "Toast", servings: 1, ingredients: [{ name: "Salt", quantity: 1, unit: "tsp" }, { name: "Bread", quantity: 2, unit: "slices" }], instructions: "Toast." }); await groceries.addRecipeIngredients(recipe); await groceries.addRecipeIngredients(recipe); const list = await groceries.getGroceries(); assertEqual(list.find((item) => item.id === manual.id)?.quantity, 3, "manual grocery edits are never overwritten by recipe import"); assertEqual(list.filter((item) => item.name === "Bread").length, 1, "repeated recipe import creates one generated item"); }
export async function testPlanRollsOverAndSnapshotsDeletedRecipe(): Promise<void> { reset(); const recipe = await recipes.createRecipe({ name: "Soup", servings: 2, ingredients: [{ name: "Water", quantity: 500, unit: "ml" }], instructions: "Heat." }); const week = plans.weekStartFor("2026-09-30"); const plan = await plans.saveAssignment(week, { date: "2026-09-30", slot: "dinner", recipeId: recipe.id }); await recipes.deleteRecipe(recipe.id); assertEqual((await plans.getPlan(week)).assignments[0].recipeSnapshot?.name, "Soup", "plan safely retains a deleted recipe snapshot"); assertEqual(plan.weekStart, "2026-09-28", "week start uses local Monday rollover"); }
