import { savedMutation, type DurableMutationResult } from "@/services/storage/durableMutation";
import { create } from "zustand";
import * as repository from "../services/measurementRepository";
import type { BodyMeasurement, BodyMeasurementInput } from "../types/measurement";
interface Store { measurements: BodyMeasurement[]; isHydrated: boolean; isLoading: boolean; isSaving: boolean; error: string | null; hydrate: () => Promise<void>; createMeasurement: (input: BodyMeasurementInput) => Promise<DurableMutationResult<BodyMeasurement>>; updateMeasurement: (id: string, input: BodyMeasurementInput) => Promise<DurableMutationResult<BodyMeasurement>>; deleteMeasurement: (id: string) => Promise<DurableMutationResult<void>>; clearError: () => void; }
export const useMeasurementStore = create<Store>((set) => ({ measurements: [], isHydrated: false, isLoading: false, isSaving: false, error: null,
  hydrate: async () => { set({ isLoading: true, error: null }); try { set({ measurements: await repository.getMeasurements(), isHydrated: true, isLoading: false }); } catch (error) { set({ isHydrated: true, isLoading: false, error: "Measurement data needs recovery before it can be used." }); throw error; } },
  createMeasurement: async (input) => { set({ isSaving: true, error: null }); try { const value = await repository.createMeasurement(input); set((state) => ({ measurements: [...state.measurements, value], isSaving: false })); return savedMutation(value); } catch (error) { set({ isSaving: false, error: "Could not save that measurement." }); throw error; } },
  updateMeasurement: async (id, input) => { set({ isSaving: true, error: null }); try { const value = await repository.updateMeasurement(id, input); set((state) => ({ measurements: state.measurements.map((item) => item.id === id ? value : item), isSaving: false })); return savedMutation(value); } catch (error) { set({ isSaving: false, error: "Could not save measurement changes." }); throw error; } },
  deleteMeasurement: async (id) => { set({ isSaving: true, error: null }); try { await repository.deleteMeasurement(id); set((state) => ({ measurements: state.measurements.filter((item) => item.id !== id), isSaving: false })); return savedMutation(undefined); } catch (error) { set({ isSaving: false, error: "Could not delete that measurement." }); throw error; } }, clearError: () => set({ error: null }),
}));
