import { BottomSheet } from "@/components/ui/BottomSheet";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { EmptyState } from "@/components/ui/EmptyState";
import { Input } from "@/components/ui/Input";
import { Screen } from "@/components/ui/Screen";
import { Text } from "@/components/ui/Text";
import { parseNzdAmountToMinor } from "@/features/budget/services/budgetMoney";
import { calculateBudgetTotals } from "@/features/budget/services/budgetSummary";
import { useBudgetCategoryStore } from "@/features/budget/store/useBudgetCategoryStore";
import { useBudgetTransactionStore } from "@/features/budget/store/useBudgetTransactionStore";
import type { BudgetCategory } from "@/features/budget/types/budgetCategory";
import type { BudgetTransaction, BudgetTransactionType } from "@/features/budget/types/budgetTransaction";
import { MoreScreenHeader } from "@/features/more/components";
import { Colors, Spacing } from "@/theme/tokens";
import { toLocalDateKey } from "@/utils/dateTime";
import { Pencil, Plus, Trash2, Wallet } from "lucide-react-native";
import { useMemo, useRef, useState } from "react";
import { ActivityIndicator, Alert, StyleSheet, TouchableOpacity, View } from "react-native";

const money = new Intl.NumberFormat("en-NZ", { style: "currency", currency: "NZD" });
const formatMoney = (minor: number) => money.format(minor / 100);

export default function BudgetScreen() {
  const categories = useBudgetCategoryStore(); const ledger = useBudgetTransactionStore();
  const [categoryForm, setCategoryForm] = useState<BudgetCategory | "new" | null>(null);
  const [transactionForm, setTransactionForm] = useState<BudgetTransaction | "new" | null>(null);
  const [name, setName] = useState(""); const [amount, setAmount] = useState(""); const [date, setDate] = useState("");
  const [type, setType] = useState<BudgetTransactionType>("expense"); const [categoryId, setCategoryId] = useState("");
  const [formError, setFormError] = useState<string | null>(null); const submitting = useRef(false);
  const totals = useMemo(() => calculateBudgetTotals(categories.categories, ledger.transactions, toLocalDateKey()), [categories.categories, ledger.transactions]);

  const openCategory = (value?: BudgetCategory) => { setCategoryForm(value ?? "new"); setName(value?.name ?? ""); setAmount(value ? (value.plannedAmountMinor / 100).toFixed(2) : ""); setFormError(null); };
  const openTransaction = (value?: BudgetTransaction) => { setTransactionForm(value ?? "new"); setName(value?.title ?? ""); setAmount(value ? (value.amountMinor / 100).toFixed(2) : ""); setDate(value?.date ?? toLocalDateKey()); setType(value?.type ?? "expense"); setCategoryId(value?.categoryId ?? categories.categories[0]?.id ?? ""); setFormError(null); };
  const submitCategory = async () => { const minor = parseNzdAmountToMinor(amount); if (!name.trim() || minor === null) return setFormError("Enter a name and positive amount with no more than two decimal places."); if (submitting.current) return; submitting.current = true; try { if (categoryForm !== "new" && categoryForm) await categories.updateCategory(categoryForm.id, { name, plannedAmountMinor: minor }); else await categories.createCategory({ name, plannedAmountMinor: minor }); setCategoryForm(null); } catch { setFormError("Could not save this category. Please retry."); } finally { submitting.current = false; } };
  const submitTransaction = async () => { const minor = parseNzdAmountToMinor(amount); if (!name.trim() || minor === null || !date || (type === "expense" && !categoryId)) return setFormError("Complete the title, exact amount, date and expense category."); if (submitting.current) return; submitting.current = true; const input = { type, title: name, amountMinor: minor, date, categoryId: type === "expense" ? categoryId : null }; try { if (transactionForm !== "new" && transactionForm) await ledger.updateTransaction(transactionForm.id, input); else await ledger.createTransaction(input); setTransactionForm(null); } catch { setFormError("Could not save this transaction. Please retry."); } finally { submitting.current = false; } };

  if (!categories.isHydrated || !ledger.isHydrated || categories.isLoading || ledger.isLoading) return <Screen padded centered><ActivityIndicator color={Colors.primary}/><Text>Loading budget and ledger…</Text></Screen>;
  return <Screen scrollable padded><MoreScreenHeader title="Budget" subtitle={`${totals.periodKey} · NZD`}/>
    <Card variant="gradient" style={styles.summary}><Text color={Colors.textInverse} variant="caption">Monthly budget</Text><Text color={Colors.textInverse} variant="heading">{formatMoney(totals.remainingMinor)} remaining</Text><Text color={Colors.textInverse} variant="small">{formatMoney(totals.expenseMinor)} spent · {formatMoney(totals.plannedMinor)} planned · {formatMoney(totals.incomeMinor)} income</Text></Card>
    {(categories.error || ledger.error) && <Card style={styles.error}><Text color={Colors.danger} accessibilityRole="alert">{categories.error ?? ledger.error}</Text></Card>}
    <View style={styles.heading}><Text variant="heading">Categories</Text><Button size="sm" onPress={() => openCategory()} leftIcon={<Plus size={16} color={Colors.textInverse}/>}>Add</Button></View>
    {categories.categories.length === 0 ? <EmptyState icon={<Wallet size={36} color={Colors.primary}/>} title="No budget categories" description="Add a monthly category before recording expenses." actionLabel="Add category" onAction={() => openCategory()}/> : <View style={styles.list}>{totals.categories.map((total) => { const category = categories.categories.find((item) => item.id === total.categoryId)!; return <Card key={category.id} style={styles.row}><View style={styles.info}><Text>{category.name}</Text><Text variant="caption" color={Colors.textSecondary}>{formatMoney(total.expenseMinor)} spent · {formatMoney(total.plannedMinor)} limit</Text></View><TouchableOpacity style={styles.action} onPress={() => openCategory(category)} accessibilityLabel={`Edit ${category.name}`}><Pencil size={18}/></TouchableOpacity><TouchableOpacity style={styles.action} accessibilityLabel={`Delete ${category.name}`} onPress={() => Alert.alert("Delete category?", "Existing transactions keep a category snapshot and remain in totals.", [{ text: "Cancel" }, { text: "Delete", style: "destructive", onPress: () => void categories.deleteCategory(category.id) }])}><Trash2 size={18} color={Colors.danger}/></TouchableOpacity></Card>; })}</View>}
    <View style={styles.heading}><Text variant="heading">Income and expenses</Text><Button size="sm" disabled={categories.categories.length === 0} onPress={() => openTransaction()} leftIcon={<Plus size={16} color={Colors.textInverse}/>}>Add</Button></View>
    {ledger.transactions.length === 0 ? <EmptyState title="No transactions this month" description="Add an expense or manual income record. Balances derive only from this ledger." actionLabel={categories.categories.length ? "Add transaction" : undefined} onAction={categories.categories.length ? () => openTransaction() : undefined}/> : <View style={styles.list}>{ledger.transactions.slice().sort((a,b) => b.date.localeCompare(a.date)).map((item) => <Card key={item.id} style={styles.row}><View style={styles.info}><Text>{item.title}</Text><Text variant="caption" color={Colors.textSecondary}>{item.date} · {item.type === "expense" ? item.categoryNameSnapshot : "Income"}</Text></View><Text color={item.type === "expense" ? Colors.danger : Colors.success}>{item.type === "expense" ? "−" : "+"}{formatMoney(item.amountMinor)}</Text><TouchableOpacity style={styles.action} onPress={() => openTransaction(item)} accessibilityLabel={`Edit ${item.title}`}><Pencil size={18}/></TouchableOpacity><TouchableOpacity style={styles.action} onPress={() => Alert.alert("Delete transaction?", "Budget totals update immediately.", [{ text: "Cancel" }, { text: "Delete", style: "destructive", onPress: () => void ledger.deleteTransaction(item.id) }])} accessibilityLabel={`Delete ${item.title}`}><Trash2 size={18} color={Colors.danger}/></TouchableOpacity></Card>)}</View>}
    <BottomSheet visible={categoryForm !== null} onClose={() => setCategoryForm(null)}><Text variant="heading">{categoryForm === "new" ? "New category" : "Edit category"}</Text><View style={styles.form}><Input label="Category name" value={name} onChangeText={setName}/><Input label="Monthly limit (NZD)" value={amount} onChangeText={setAmount} keyboardType="decimal-pad"/>{formError && <Text color={Colors.danger}>{formError}</Text>}<View style={styles.buttons}><Button style={styles.button} variant="ghost" onPress={() => setCategoryForm(null)}>Cancel</Button><Button style={styles.button} onPress={() => void submitCategory()}>Save</Button></View></View></BottomSheet>
    <BottomSheet visible={transactionForm !== null} onClose={() => setTransactionForm(null)} snapPoint={0.75}><Text variant="heading">{transactionForm === "new" ? "New transaction" : "Edit transaction"}</Text><View style={styles.form}><View style={styles.buttons}><Button style={styles.button} variant={type === "expense" ? "primary" : "ghost"} onPress={() => setType("expense")}>Expense</Button><Button style={styles.button} variant={type === "income" ? "primary" : "ghost"} onPress={() => setType("income")}>Income</Button></View><Input label="Title or description" value={name} onChangeText={setName}/><Input label="Amount (NZD)" value={amount} onChangeText={setAmount} keyboardType="decimal-pad"/><Input label="Date (YYYY-MM-DD)" value={date} onChangeText={setDate}/>{type === "expense" && <View><Text variant="label" color={Colors.textSecondary}>Category</Text><View style={styles.choices}>{categories.categories.map((item) => <Button key={item.id} size="sm" variant={categoryId === item.id ? "primary" : "ghost"} onPress={() => setCategoryId(item.id)}>{item.name}</Button>)}</View></View>}{formError && <Text color={Colors.danger}>{formError}</Text>}<View style={styles.buttons}><Button style={styles.button} variant="ghost" onPress={() => setTransactionForm(null)}>Cancel</Button><Button style={styles.button} loading={ledger.isSaving} onPress={() => void submitTransaction()}>Save</Button></View></View></BottomSheet>
  </Screen>;
}
const styles = StyleSheet.create({ summary: { padding: Spacing.xl, gap: Spacing.sm, marginBottom: Spacing.lg }, error: { borderColor: Colors.danger, borderWidth: 1, marginBottom: Spacing.md }, heading: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: Spacing.lg, marginBottom: Spacing.md }, list: { gap: Spacing.md }, row: { padding: Spacing.md, flexDirection: "row", alignItems: "center", gap: Spacing.sm }, info: { flex: 1, gap: Spacing.xs }, action: { width: 44, height: 44, alignItems: "center", justifyContent: "center" }, form: { gap: Spacing.md, marginTop: Spacing.lg }, buttons: { flexDirection: "row", gap: Spacing.sm }, button: { flex: 1 }, choices: { flexDirection: "row", flexWrap: "wrap", gap: Spacing.sm, marginTop: Spacing.sm } });
