import { BottomSheet } from "@/components/ui/BottomSheet";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { EmptyState } from "@/components/ui/EmptyState";
import { Input } from "@/components/ui/Input";
import { Screen } from "@/components/ui/Screen";
import { Text } from "@/components/ui/Text";
import { measurementHistoryForType } from "@/features/measurements/services/measurementSelectors";
import { formatMeasurementValue, parseMeasurementValue } from "@/features/measurements/services/measurementValue";
import { useMeasurementStore } from "@/features/measurements/store/useMeasurementStore";
import { measurementTypes, type BodyMeasurement, type MeasurementType, type MeasurementUnit } from "@/features/measurements/types/measurement";
import { MoreScreenHeader } from "@/features/more/components";
import { Colors, Radius, Spacing } from "@/theme/tokens";
import { formatLocalDate, toLocalDateKey } from "@/utils/dateTime";
import { Pencil, Plus, Ruler, Trash2 } from "lucide-react-native";
import { useMemo, useRef, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, TouchableOpacity, View } from "react-native";

const label = (type: MeasurementType) => type.split("-").map((part) => part[0].toUpperCase() + part.slice(1)).join(" ");
export default function MeasurementsScreen() {
  const store = useMeasurementStore(); const [selectedType, setSelectedType] = useState<MeasurementType>("waist"); const history = useMemo(() => measurementHistoryForType(store.measurements, selectedType), [store.measurements, selectedType]);
  const [form, setForm] = useState<BodyMeasurement | "new" | null>(null); const [type, setType] = useState<MeasurementType>("waist"); const [unit, setUnit] = useState<MeasurementUnit>("cm"); const [value, setValue] = useState(""); const [date, setDate] = useState(""); const [formError, setFormError] = useState<string | null>(null); const submitting = useRef(false);
  const open = (entry?: BodyMeasurement) => { setForm(entry ?? "new"); setType(entry?.type ?? selectedType); setUnit(entry?.unit ?? "cm"); setValue(entry ? formatMeasurementValue(entry.valueMilli) : ""); setDate(entry?.date ?? toLocalDateKey()); setFormError(null); };
  const submit = async () => { const valueMilli = parseMeasurementValue(value); if (valueMilli === null || !date) return setFormError("Enter a positive value with up to three decimal places and a valid date."); if (submitting.current) return; submitting.current = true; try { const input = { type, unit, valueMilli, date }; if (form !== "new" && form) await store.updateMeasurement(form.id, input); else await store.createMeasurement(input); setSelectedType(type); setForm(null); } catch { setFormError("Could not save this measurement. Please retry."); } finally { submitting.current = false; } };
  if (!store.isHydrated || store.isLoading) return <Screen padded centered><ActivityIndicator color={Colors.primary}/><Text>Loading measurements…</Text></Screen>;
  return <Screen scrollable padded><MoreScreenHeader title="Body Measurements" subtitle="Manual records by measurement type"/>
    {store.error && <Card style={styles.error}><Text color={Colors.danger} accessibilityRole="alert">{store.error}</Text><Button size="sm" variant="ghost" onPress={store.clearError}>Dismiss</Button></Card>}
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{measurementTypes.map((item) => <Button key={item} size="sm" variant={item === selectedType ? "primary" : "ghost"} onPress={() => setSelectedType(item)}>{label(item)}</Button>)}</ScrollView>
    {history.length === 0 ? <EmptyState icon={<Ruler size={36} color={Colors.primary}/>} title={`No ${label(selectedType).toLowerCase()} measurements`} description="Add a dated measurement to begin this history." actionLabel="Add measurement" onAction={() => open()}/> : <View style={styles.list}>{history.map((entry) => <Card key={entry.id} style={styles.row}><View style={styles.icon}><Ruler size={18} color={Colors.primary}/></View><View style={styles.info}><Text>{formatMeasurementValue(entry.valueMilli)} {entry.unit}</Text><Text variant="caption" color={Colors.textSecondary}>{formatLocalDate(entry.date, { year: "numeric", month: "short", day: "numeric" })}</Text></View><TouchableOpacity style={styles.action} onPress={() => open(entry)} accessibilityLabel={`Edit ${label(entry.type)} measurement`}><Pencil size={18}/></TouchableOpacity><TouchableOpacity style={styles.action} onPress={() => Alert.alert("Delete measurement?", "This removes the record from this history.", [{ text: "Cancel" }, { text: "Delete", style: "destructive", onPress: () => void store.deleteMeasurement(entry.id) }])} accessibilityLabel={`Delete ${label(entry.type)} measurement`}><Trash2 size={18} color={Colors.danger}/></TouchableOpacity></Card>)}</View>}
    <Button style={styles.add} leftIcon={<Plus size={18} color={Colors.textInverse}/>} onPress={() => open()}>Add measurement</Button>
    <BottomSheet visible={form !== null} onClose={() => setForm(null)}><Text variant="heading">{form === "new" ? "Add measurement" : "Edit measurement"}</Text><View style={styles.form}><Text variant="label">Measurement type</Text><View style={styles.wrap}>{measurementTypes.map((item) => <Button key={item} size="sm" variant={item === type ? "primary" : "ghost"} onPress={() => setType(item)}>{label(item)}</Button>)}</View><Text variant="label">Unit</Text><View style={styles.buttons}><Button style={styles.flex} size="sm" variant={unit === "cm" ? "primary" : "ghost"} onPress={() => setUnit("cm")}>cm</Button><Button style={styles.flex} size="sm" variant={unit === "in" ? "primary" : "ghost"} onPress={() => setUnit("in")}>in</Button></View><Input label={`Value (${unit})`} value={value} onChangeText={setValue} keyboardType="decimal-pad"/><Input label="Date (YYYY-MM-DD)" value={date} onChangeText={setDate}/>{formError && <Text color={Colors.danger} accessibilityRole="alert">{formError}</Text>}<View style={styles.buttons}><Button style={styles.flex} variant="ghost" onPress={() => setForm(null)}>Cancel</Button><Button style={styles.flex} loading={store.isSaving} onPress={() => void submit()}>Save</Button></View></View></BottomSheet>
  </Screen>;
}
const styles = StyleSheet.create({ error: { gap: Spacing.sm, borderColor: Colors.danger, borderWidth: 1, marginBottom: Spacing.md }, filters: { gap: Spacing.sm, paddingBottom: Spacing.lg }, list: { gap: Spacing.md }, row: { padding: Spacing.md, flexDirection: "row", alignItems: "center", gap: Spacing.sm }, icon: { width: 44, height: 44, borderRadius: Radius.lg, backgroundColor: `${Colors.primary}15`, alignItems: "center", justifyContent: "center" }, info: { flex: 1, gap: Spacing.xs }, action: { width: 44, height: 44, alignItems: "center", justifyContent: "center" }, add: { marginTop: Spacing.xl }, form: { gap: Spacing.md, marginTop: Spacing.lg }, buttons: { flexDirection: "row", gap: Spacing.sm }, wrap: { flexDirection: "row", flexWrap: "wrap", gap: Spacing.sm }, flex: { flex: 1 } });
