import { BottomSheet } from "@/components/ui/BottomSheet";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { EmptyState } from "@/components/ui/EmptyState";
import { Input } from "@/components/ui/Input";
import { Screen } from "@/components/ui/Screen";
import { Text } from "@/components/ui/Text";
import { useMealStore } from "@/features/meals/store/useMealStore";
import { useRecipeStore } from "@/features/recipes/store/useRecipeStore";
import type { Recipe } from "@/features/recipes/types/recipe";
import { MoreScreenHeader } from "@/features/more/components";
import { useLocalDay } from "@/hooks/useLocalDay";
import { Colors, Spacing } from "@/theme/tokens";
import { Pencil, Plus, Trash2, Utensils } from "lucide-react-native";
import { useEffect, useState } from "react";
import { ActivityIndicator, Alert, ScrollView, StyleSheet, TouchableOpacity, View } from "react-native";
type DraftIngredient = { name: string; quantity: string; unit: string };
const blank = (): DraftIngredient => ({ name: "", quantity: "", unit: "" });
export default function RecipesScreen() {
  const recipes = useRecipeStore(); const meals = useMealStore(); const today = useLocalDay(); const [editing, setEditing] = useState<Recipe | null>(null); const [visible, setVisible] = useState(false); const [name, setName] = useState(""); const [servings, setServings] = useState("1"); const [instructions, setInstructions] = useState(""); const [ingredients, setIngredients] = useState<DraftIngredient[]>([blank()]); const [formError, setFormError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!recipes.isHydrated && !recipes.isLoading) void recipes.hydrate().catch(() => undefined); if (!meals.isHydrated && !meals.isLoading) void meals.hydrate().catch(() => undefined); }, [recipes, meals]);
  const open = (recipe?: Recipe) => { setEditing(recipe ?? null); setName(recipe?.name ?? ""); setServings(String(recipe?.servings ?? 1)); setInstructions(recipe?.instructions ?? ""); setIngredients(recipe?.ingredients.map((i) => ({ name: i.name, quantity: String(i.quantity), unit: i.unit })) ?? [blank()]); setFormError(null); setVisible(true); };
  const save = async () => { const parsed = ingredients.map((i) => ({ name: i.name.trim(), quantity: Number(i.quantity), unit: i.unit.trim() })); if (!name.trim() || !instructions.trim() || !(Number(servings) > 0) || !parsed.length || parsed.some((i) => !i.name || !i.unit || !(i.quantity > 0))) { setFormError("Add a name, positive servings, instructions, and every ingredient's name, quantity and unit."); return; } setSaving(true); try { if (editing) await recipes.updateRecipe(editing.id, { name, servings: Number(servings), instructions, ingredients: parsed }); else await recipes.createRecipe({ name, servings: Number(servings), instructions, ingredients: parsed }); setVisible(false); } catch { setFormError("Could not save this recipe. Please try again."); } finally { setSaving(false); } };
  const log = async (recipe: Recipe) => { try { await meals.createMealFromRecipe(recipe, { date: today, mealType: "dinner" }); Alert.alert("Logged as consumed", `${recipe.name} was logged as dinner today. Its recipe snapshot is now fixed in meal history.`); } catch { Alert.alert("Could not log meal", "Please try again."); } };
  if (!recipes.isHydrated || recipes.isLoading) return <Screen padded centered><ActivityIndicator color={Colors.primary}/><Text>Loading recipes…</Text></Screen>;
  return <Screen scrollable padded><MoreScreenHeader title="Recipes" subtitle="Save the meals you make"/>{recipes.error && <Text color={Colors.danger} accessibilityRole="alert">{recipes.error}</Text>}
    {recipes.recipes.length === 0 ? <EmptyState icon={<Utensils size={36} color={Colors.primary}/>} title="No saved recipes" description="Save ingredients and instructions for meals you make often." actionLabel="Add recipe" onAction={() => open()}/> : <View style={styles.list}>{recipes.recipes.map((recipe) => <Card key={recipe.id} style={styles.card}><View style={styles.top}><View style={styles.grow}><Text variant="body" style={styles.name}>{recipe.name}</Text><Text variant="caption" color={Colors.textSecondary}>{recipe.servings} servings · {recipe.ingredients.length} ingredients</Text></View><TouchableOpacity style={styles.icon} onPress={() => open(recipe)} accessibilityLabel={`Edit ${recipe.name}`}><Pencil size={18}/></TouchableOpacity><TouchableOpacity style={styles.icon} onPress={() => Alert.alert("Delete recipe?", "Existing consumed meals keep their saved snapshot.", [{ text: "Cancel" }, { text: "Delete", style: "destructive", onPress: () => void recipes.deleteRecipe(recipe.id) }])} accessibilityLabel={`Delete ${recipe.name}`}><Trash2 size={18} color={Colors.danger}/></TouchableOpacity></View><Text variant="small" color={Colors.textSecondary}>{recipe.ingredients.map((i) => `${i.quantity} ${i.unit} ${i.name}`).join(" · ")}</Text><Text variant="small">{recipe.instructions}</Text><Button size="sm" variant="secondary" onPress={() => void log(recipe)}>Log as dinner today</Button></Card>)}</View>}<Button style={styles.add} leftIcon={<Plus size={18} color={Colors.textInverse}/>} onPress={() => open()}>Add recipe</Button>
    <BottomSheet visible={visible} onClose={saving ? undefined : () => setVisible(false)} style={styles.sheet}><Text variant="heading">{editing ? "Edit recipe" : "New recipe"}</Text><ScrollView contentContainerStyle={styles.form} keyboardShouldPersistTaps="handled"><Input label="Recipe name" value={name} onChangeText={setName}/><Input label="Servings" value={servings} onChangeText={setServings} keyboardType="decimal-pad"/><Input label="Instructions" value={instructions} onChangeText={setInstructions} multiline/>{ingredients.map((ingredient, index) => <View key={index} style={styles.ingredient}><Input label={`Ingredient ${index + 1}`} value={ingredient.name} onChangeText={(value) => setIngredients((all) => all.map((v, i) => i === index ? { ...v, name: value } : v))}/><Input label="Qty" value={ingredient.quantity} onChangeText={(value) => setIngredients((all) => all.map((v, i) => i === index ? { ...v, quantity: value } : v))} keyboardType="decimal-pad"/><Input label="Unit" value={ingredient.unit} onChangeText={(value) => setIngredients((all) => all.map((v, i) => i === index ? { ...v, unit: value } : v))}/>{ingredients.length > 1 && <Button size="sm" variant="ghost" onPress={() => setIngredients((all) => all.filter((_, i) => i !== index))}>Remove ingredient</Button>}</View>)}<Button size="sm" variant="ghost" onPress={() => setIngredients((all) => [...all, blank()])}>Add ingredient</Button>{formError && <Text color={Colors.danger} accessibilityRole="alert">{formError}</Text>}<Button loading={saving} onPress={() => void save()}>{editing ? "Save changes" : "Save recipe"}</Button></ScrollView></BottomSheet></Screen>;
}
const styles = StyleSheet.create({ list: { gap: Spacing.md }, card: { padding: Spacing.md, gap: Spacing.sm }, top: { flexDirection: "row", alignItems: "center" }, grow: { flex: 1 }, name: { fontWeight: "600" }, icon: { width: 44, height: 44, alignItems: "center", justifyContent: "center" }, add: { marginTop: Spacing.xl }, sheet: { maxHeight: "94%" }, form: { gap: Spacing.md, paddingVertical: Spacing.lg }, ingredient: { gap: Spacing.sm, paddingBottom: Spacing.sm, borderBottomColor: Colors.border, borderBottomWidth: 1 } });
