import * as repository from "@/features/workouts/services/workoutRepository";
import { workoutSummaryForRange } from "@/features/workouts/services/workoutSelectors";
import { useWorkoutStore } from "@/features/workouts/store/useWorkoutStore";
import { DurableMutationError } from "@/services/storage/durableMutation";
import { deleteKey } from "@/services/storage/mmkv";
import { StorageKeys } from "@/services/storage/storageKeys";
import { assert, assertEqual } from "../testUtils";

function reset(): void { deleteKey(StorageKeys.WORKOUTS); useWorkoutStore.setState({ workouts: [], isHydrated: false, isLoading: false, isSaving: false, error: null }); }
export async function testWorkoutDateTotalsAndOptionalCalories(): Promise<void> { reset(); await repository.createWorkout({ activity: "Walk", date: "2026-09-01", durationMinutes: 30, calorieEstimate: 120 }); await repository.createWorkout({ activity: "Yoga", date: "2026-09-02", durationMinutes: 45 }); await repository.createWorkout({ activity: "Cycle", date: "2026-09-08", durationMinutes: 60, calorieEstimate: 300 }); const summary = workoutSummaryForRange(await repository.getWorkouts(), "2026-09-01", "2026-09-08"); assertEqual(summary.count, 2, "range excludes its end boundary"); assertEqual(summary.durationMinutes, 75, "duration derives from selected records"); assertEqual(summary.knownCalories, 120, "only supplied calorie estimates are summed"); assertEqual(summary.unknownCalorieCount, 1, "missing calories remain explicit"); }
export async function testWorkoutEditDeleteAndRestart(): Promise<void> { reset(); const value = await repository.createWorkout({ activity: "Swim", date: "2026-09-04", durationMinutes: 25 }); await repository.updateWorkout(value.id, { activity: "Pool swim", date: "2026-09-05", durationMinutes: 40, calorieEstimate: 180 }); assertEqual((await repository.getWorkouts())[0].durationMinutes, 40, "editing updates the canonical record"); await useWorkoutStore.getState().hydrate(); assertEqual(useWorkoutStore.getState().workouts[0].activity, "Pool swim", "workout survives restart hydration"); await repository.deleteWorkout(value.id); assertEqual((await repository.getWorkouts()).length, 0, "deletion removes the workout from active history"); }
export async function testWorkoutDurationAndDateValidation(): Promise<void> { reset(); for (const input of [{ activity: "Run", date: "2026-09-01", durationMinutes: 0 }, { activity: "Run", date: "bad", durationMinutes: 10 }, { activity: "Run", date: "2026-09-01", durationMinutes: 1.5 }]) { let failure: unknown; try { await repository.createWorkout(input); } catch (error) { failure = error; } assert(failure instanceof DurableMutationError, "invalid workout input is rejected"); } }
