import { DurableMutationError, SerializedMutationQueue, type DurableMutationOperation } from "@/services/storage/durableMutation";
import { weightStorageDefinition } from "@/services/storage/domainSchemas";
import { loadVersionedData, saveVersionedData } from "@/services/storage/versionedStorage";
import { isLocalDateKey } from "@/utils/dateTime";
import type { WeightEntry, WeightEntryInput, WeightState, WeightUnit } from "../types/weight";
const queue = new SerializedMutationQueue(); const load = () => loadVersionedData(weightStorageDefinition).data; const save = (value: WeightState) => saveVersionedData(weightStorageDefinition, value);
function validate(input: WeightEntryInput, operation: DurableMutationOperation): WeightEntryInput { if (!Number.isSafeInteger(input.grams) || input.grams <= 0) throw new DurableMutationError("weight", operation, "invalid-input", "Weight must be greater than zero."); if (!isLocalDateKey(input.date)) throw new DurableMutationError("weight", operation, "invalid-input", "Choose a valid local date."); return { ...input, note: input.note?.trim() || undefined }; }
function mutate<T>(operation: DurableMutationOperation, work: () => T): Promise<T> { return queue.run(() => { try { return work(); } catch (cause) { if (cause instanceof DurableMutationError) throw cause; throw new DurableMutationError("weight", operation, "write-failed", "Weight changes could not be saved.", cause); } }); }
export async function getWeightState(): Promise<WeightState> { await queue.waitForIdle(); return load(); }
export function createWeightEntry(input: WeightEntryInput): Promise<WeightEntry> { return mutate("create", () => { const valid = validate(input, "create"); const state = load(); const now = new Date().toISOString(); const entry = { ...valid, id: `weight_${Date.now()}_${Math.random().toString(36).slice(2, 10)}`, createdAt: now, updatedAt: now, deletedAt: null, version: 1 }; save({ ...state, entries: [...state.entries, entry], updatedAt: now, version: state.version + 1 }); return entry; }); }
export function updateWeightEntry(id: string, input: WeightEntryInput): Promise<WeightEntry> { return mutate("update", () => { const valid = validate(input, "update"); const state = load(); const index = state.entries.findIndex((entry) => entry.id === id && !entry.deletedAt); if (index < 0) throw new DurableMutationError("weight", "update", "not-found", "That weight entry no longer exists."); const entry = { ...state.entries[index], ...valid, updatedAt: new Date().toISOString(), version: state.entries[index].version + 1 }; const entries = [...state.entries]; entries[index] = entry; save({ ...state, entries, updatedAt: entry.updatedAt, version: state.version + 1 }); return entry; }); }
export function deleteWeightEntry(id: string): Promise<void> { return mutate("delete", () => { const state = load(); const index = state.entries.findIndex((entry) => entry.id === id && !entry.deletedAt); if (index < 0) return; const now = new Date().toISOString(); const entries = [...state.entries]; entries[index] = { ...entries[index], deletedAt: now, updatedAt: now, version: entries[index].version + 1 }; save({ ...state, entries, updatedAt: now, version: state.version + 1 }); }); }
export function setWeightUnit(preferredUnit: WeightUnit): Promise<WeightState> { return mutate("update", () => { if (preferredUnit !== "kg" && preferredUnit !== "lb") throw new DurableMutationError("weight", "update", "invalid-input", "Choose kilograms or pounds."); const state = load(); const value = { ...state, preferredUnit, updatedAt: new Date().toISOString(), version: state.version + 1 }; save(value); return value; }); }
